/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    App: typeof import('./App.vue')['default']
    Cart: typeof import('./views/Cart/index.vue')['default']
    CommonFooter: typeof import('./components/CommonFooter/index.vue')['default']
    CommonHeader: typeof import('./components/CommonHeader/index.vue')['default']
    Home: typeof import('./views/Home/index.vue')['default']
    Mine: typeof import('./views/Mine/index.vue')['default']
    NotFound: typeof import('./views/NotFound/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Test: typeof import('./components/Test.vue')['default']
    VanButton: typeof import('vant/es')['Button']
    VanConfigProvide: typeof import('vant/es')['ConfigProvide']
    VanConfigProvider: typeof import('vant/es')['ConfigProvider']
    VanIcon: typeof import('vant/es')['Icon']
    VanSearch: typeof import('vant/es')['Search']
    VanTabbar: typeof import('vant/es')['Tabbar']
    VanTabbarItem: typeof import('vant/es')['TabbarItem']
  }
}
